
name: Annotations Failure Action

description: Allow to turn certain annotations (e.g. from problem matchers) into run failures.

author: CERN, ROOT Project, Ole Morud

branding:
  icon: 'x-octagon'
  color: 'orange'

inputs:
  filter:
    description: 'Regex to filter annotations, matching annotations causes job failures'
    required: false

runs:
  using: 'node16'
  main: 'src/annotations.mjs'
