
name: Annotations Failure Action

description: Allow to turn certain annotations (e.g. from problem matchers) into run failures.

author: CERN, ROOT Project, Ole Morud

branding:
  icon: 'alert-octagon'
  color: 'orange'

inputs:
  GH_TOKEN:
    description: 'GitHub token, required to read workflow annotations'
    required: true
  workflow_id:
    description: 'Workflow ID to read annotations from'
    required: true
  filter:
    description: 'Regex to filter annotations, matching annotations causes job failures'
    required: false

runs:
  using: 'node16'
  main: 'src/annotations.mjs'
