
name: Create and read annotations

on:
  # Enables manual start of workflow
  push:
  workflow_dispatch:

jobs:
  #create_annotations_in_matrix:
  #  name: Create annotations
  #  runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #      level: ["warning", "error"]
  #      message: ["foo", "bar"]
  #  steps:

  compile-awful-code:
    name: Compile awful code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add problem matcher
        uses: olemorud/gcc-problem-matcher@v1.0

      - name: Compile bad code
        run: c++ -Wall -Wextra test/bad-code.cpp

      - name: Create annotation that should not be matched
        run: echo "::error::foo"

  read_annotations:
    name: Read annotations
    needs: [compile-awful-code]
    runs-on: ubuntu-latest

    permissions:
      checks: write
      actions: read

    steps:
      - uses: actions/checkout@v3

      - name: npm install
        run: npm ci

      - name: Print the annotations of this run
        uses: ./
        with:
          workflow_id: ${{ github.run_id }}
          filter: '\[-W[a-zA-Z-]+?\]'
          GH_TOKEN: ${{ github.token }}

  event_file:
    name: "Upload Event Payload"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Event File
        path: ${{ github.event_path }}
